name: Python CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source venv/bin/activate
          coverage run -m unittest discover tests
          coverage xml

      - name: Upload coverage to SonarCloud
        env:
          SONAR_TOKEN: ${{ secrets.3330d94cde115cec1d69c66eb5ba68f94005008c }}
        run: |
          sonar-scanner
